import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../../utils/logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const uploadsDir = path.join(__dirname, '../../uploads');

export class PDFService {
  /**
   * Generate PDF report from analysis
   */
  static async generateReport(reportData) {
    fs.mkdirSync(uploadsDir, { recursive: true });

    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage();

    const htmlContent = this._generateHTMLReport(reportData);

    await page.setContent(htmlContent);
    await page.emulateMedia({ media: 'print' });

    const fileName = `report-${reportData.reportId}.pdf`;
    const pdfPath = path.join(uploadsDir, fileName);

    await page.pdf({
      path: pdfPath,
      format: 'A4',
      margin: {
        top: '20mm',
        bottom: '20mm',
        left: '15mm',
        right: '15mm',
      },
    });

    await browser.close();
    logger.info(`PDF report generated: ${pdfPath}`);

    return {
      diskPath: pdfPath,
      publicUrl: `/uploads/${fileName}`,
    };
  }

  /**
   * Generate HTML content for PDF
   */
  static _generateHTMLReport(data) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Medical Report</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            color: #333;
            line-height: 1.6;
          }
          .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            border-bottom: 3px solid #007bff;
            padding-bottom: 20px;
            margin-bottom: 30px;
            text-align: center;
          }
          .header h1 {
            color: #007bff;
            margin: 0;
          }
          .disclaimer {
            background-color: #fff3cd;
            border: 1px solid #ffc107;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
            font-size: 12px;
          }
          .section {
            margin: 25px 0;
            page-break-inside: avoid;
          }
          .section h2 {
            color: #007bff;
            border-bottom: 2px solid #e0e0e0;
            padding-bottom: 10px;
            font-size: 18px;
          }
          .section-content {
            padding: 15px 0;
          }
          .risk-score {
            font-size: 36px;
            font-weight: bold;
            color: ${data.aiAnalysis?.riskLevel === 'High' ? '#dc3545' : data.aiAnalysis?.riskLevel === 'Medium' ? '#ffc107' : '#28a745'};
            text-align: center;
            padding: 20px;
            border: 2px solid currentColor;
            border-radius: 10px;
            margin: 20px 0;
          }
          .risk-level {
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            color: ${data.aiAnalysis?.riskLevel === 'High' ? '#dc3545' : data.aiAnalysis?.riskLevel === 'Medium' ? '#ffc107' : '#28a745'};
            margin-top: 10px;
          }
          .patient-info {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
          }
          .info-item {
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
          }
          .info-label {
            font-weight: bold;
            color: #007bff;
          }
          .medicine-item {
            padding: 15px;
            background-color: #f8f9fa;
            border-left: 4px solid #007bff;
            margin: 10px 0;
            border-radius: 3px;
          }
          .doctor-item {
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 10px 0;
          }
          .footer {
            border-top: 2px solid #e0e0e0;
            padding-top: 20px;
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Healthcare Assistant - Medical Report</h1>
            <p>Preliminary Health Assessment Report</p>
          </div>

          <div class="disclaimer">
            <strong>⚠️ MEDICAL DISCLAIMER:</strong>
            This report is generated by an AI system for preliminary assessment purposes only.
            It is NOT a substitute for professional medical diagnosis or treatment.
            Please consult a licensed healthcare professional for accurate diagnosis and treatment.
            In case of emergency, call your local emergency services immediately.
          </div>

          <div class="section">
            <h2>Patient Information</h2>
            <div class="patient-info">
              <div class="info-item">
                <div class="info-label">Disease Area:</div>
                <div>${data.disease}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Age:</div>
                <div>${data.personalDetails?.age || 'Not provided'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Gender:</div>
                <div>${data.personalDetails?.gender || 'Not provided'}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Report Date:</div>
                <div>${new Date().toLocaleDateString()}</div>
              </div>
            </div>
          </div>

          <div class="section">
            <h2>Health Assessment Score</h2>
            <div class="risk-score">${data.aiAnalysis?.score || 50}</div>
            <div class="risk-level">Risk Level: ${data.aiAnalysis?.riskLevel || 'Medium'}</div>
          </div>

          <div class="section">
            <h2>Summary</h2>
            <div class="section-content">
              ${data.aiAnalysis?.summary || 'No summary available'}
            </div>
          </div>

          ${
            data.aiAnalysis?.likelyCondition || data.aiAnalysis?.probableConditions?.length
              ? `
            <div class="section">
              <h2>Likely Condition Review</h2>
              <div class="section-content">
                <p><strong>Primary condition area:</strong> ${data.aiAnalysis?.likelyCondition || 'Further clinician review recommended'}</p>
                ${
                  data.aiAnalysis?.probableConditions?.length
                    ? `<ul>${data.aiAnalysis.probableConditions.map((item) => `<li>${item}</li>`).join('')}</ul>`
                    : ''
                }
              </div>
            </div>
            `
              : ''
          }

          <div class="section">
            <h2>Symptoms Analysis</h2>
            <div class="section-content">
              ${data.aiAnalysis?.symptomAnalysis || data.symptoms || 'No detailed symptom analysis available'}
            </div>
          </div>

          ${
            data.aiAnalysis?.documentAnalysis
              ? `
            <div class="section">
              <h2>Uploaded File Analysis</h2>
              <div class="section-content">
                ${data.aiAnalysis.documentAnalysis}
              </div>
            </div>
            `
              : ''
          }

          ${
            data.aiAnalysis?.riskFactors && data.aiAnalysis.riskFactors.length > 0
              ? `
            <div class="section">
              <h2>Risk Factors</h2>
              <div class="section-content">
                <ul>
                  ${data.aiAnalysis.riskFactors.map((factor) => `<li>${factor}</li>`).join('')}
                </ul>
              </div>
            </div>
            `
              : ''
          }

          ${
            data.aiAnalysis?.recommendations && data.aiAnalysis.recommendations.length > 0
              ? `
            <div class="section">
              <h2>Recommendations</h2>
              <div class="section-content">
                <ul>
                  ${data.aiAnalysis.recommendations.map((item) => `<li>${item}</li>`).join('')}
                </ul>
              </div>
            </div>
            `
              : ''
          }

          <div class="section">
            <h2>Medical Advice</h2>
            <div class="section-content">
              ${data.aiAnalysis?.medicalAdvice || 'Please consult a healthcare professional'}
            </div>
          </div>

          ${
            data.aiAnalysis?.urgentCare
              ? `
            <div class="section">
              <h2>Urgent Care Guidance</h2>
              <div class="section-content">
                ${data.aiAnalysis.urgentCare}
              </div>
            </div>
            `
              : ''
          }

          ${
            data.aiAnalysis?.suggestedMedicines && data.aiAnalysis.suggestedMedicines.length > 0
              ? `
            <div class="section">
              <h2>Suggested Medicines</h2>
              <div class="section-content">
                ${data.aiAnalysis.suggestedMedicines
                  .map(
                    (medicine) => `
                  <div class="medicine-item">
                    <strong>${medicine.name}</strong><br>
                    Dosage: ${medicine.dosage}<br>
                    Frequency: ${medicine.frequency}
                  </div>
                `
                  )
                  .join('')}
              </div>
            </div>
            `
              : ''
          }

          ${
            data.doctorSuggestions && data.doctorSuggestions.length > 0
              ? `
            <div class="section">
              <h2>Nearby Doctor Recommendations</h2>
              <div class="section-content">
                ${data.doctorSuggestions
                  .slice(0, 5)
                  .map(
                    (doctor) => `
                  <div class="doctor-item">
                    <strong>${doctor.name}</strong> - ${doctor.specialty}<br>
                    Address: ${doctor.address}<br>
                    Distance: ${doctor.distance} km<br>
                    Rating: ${doctor.rating} ⭐<br>
                    Phone: ${doctor.phoneNumber}
                  </div>
                `
                  )
                  .join('')}
              </div>
            </div>
            `
              : ''
          }

          <div class="footer">
            <p>Generated on ${new Date().toLocaleString()}</p>
            <p>This report should not be used as a replacement for professional medical advice.</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}
